# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Magicwand
                                 A QGIS plugin
 Auto-making Polygon by MapCanvas
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-07-14
        copyright            : (C) 2019 by Kanahiro Iguchi
        email                : https://twitter.com/kigchi999
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Magicwand class from file Magicwand.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .magic_wand import Magicwand
    return Magicwand(iface)
